apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deployment
spec:
  selector:
    matchLabels:
      app: guestbook
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: zzzzzzzzz.ecr.zzzzzzzz.amazonaws.com/guestbook
        ports:
        - containerPort: 8080
